# This is a workflow to help you test the unit case and show codecov

name: "build and codecov"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang:
          - 1.18
    steps:
      - name: Setup redis
        uses: supercharge/redis-github-action@1.2.0
        with:
        redis-version: 6

      - name: Install redis cli # so we can test the server
        run: sudo apt-get install -y redis-tools

      - name: Verify that redis is up
        run: redis-cli ping

      - name: "set up go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "checkout ${{ github.ref }}"
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: "run go build"
        run: go build -v ./...

      - name: "run go test and out codecov"
        run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: "upload coverage"
        uses: codecov/codecov-action@v3
